### ISSUE TITLE
Bug - Fix the github action maven CI build failure

### ISSUE THREAD

**Issue by animo93** [animo93/JRest#44]
The current github action for maven CI build is failing everytime because of `TestHttpRESTApi` class which is using a `MockServer` for testing .

So , need to check how this issue can be fixed

**Comment by thanhtamB2112004** [comment]
Hello, I am interested in your issue, can you assign this to me if it is still available?

**Comment by animo93** [comment]
Hello @thanhtamB2112004 ,

I haven't yet researched a solution for this issue . So , can you let me know what solution are you planning to implement for the same

**Comment by thanhtamB2112004** [comment]
Hello @animo93 , 
First of all, I am currently an unexperienced student and I am trying to contribute to public projects for studying purposes so if I do anything wrong or unprofessionally, please tell me.
About the bug, I tried updating the versions of plugins and remove duplicated dependencies, which are configured in pom.xml.
![image](https://github.com/user-attachments/assets/ca56b8ab-d089-4605-af8e-608f26b6806b)
Also, the CodeQL build process failed to build so I configured it to be built manually and updated some versions of actions processes:
![image](https://github.com/user-attachments/assets/af999e56-6484-4623-aef5-e2c77f7450ae)
Finally, because the update dependency graph step in maven caused range error so I skip it to test the build process
![image](https://github.com/user-attachments/assets/8a02371d-4a78-404e-9353-90b8ea49a30f)
After all the above updates, I push it to my Github repo to test it in Github actions and they worked. Please review my answer and provide my some comments. Thank you.

**Comment by animo93** [comment]
Hello @thanhtamB2112004 ,

The updates for `pom.xml` and `maven.yml` are ok , but there is no need to make any changes to the `codeql-analysis.yml` file now .

And regarding the build issue with github actions I am getting the below mentioned error before the `dependency graph` stage .
`com.animo.jRest.test.TestHttpRESTApi.testSingleStaticHeaderKey()  Time elapsed: 0.536 sec  <<< FAILURE!
org.mockserver.httpclient.SocketConnectionException: Unable to connect to socket localhost/127.0.0.1:8081
	at org.mockserver.httpclient.NettyHttpClient.sendRequest(NettyHttpClient.java:226)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:392)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:428)
	at org.mockserver.client.MockServerClient.upsert(MockServerClient.java:1493)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:84)
	at com.animo.jRest.test.TestHttpRESTApi.createExpectationForInvalidAuth(TestHttpRESTApi.java:46)
	at com.animo.jRest.test.TestHttpRESTApi.testSingleStaticHeaderKey(TestHttpRESTApi.java:60)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8081
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)`

So , are you sure that your github actions build is running fine after removing the `dependency graph` step ?

**Comment by thanhtamB2112004** [comment]
- Hi @animo93 , yes my Maven build running fine with the previously mentioned updates and without the dependency graph step.
![image](https://github.com/user-attachments/assets/14a95cde-05d9-4209-aa18-3f6e611818af)
- But what version of actions should I use? Because if I keep the versions that your codeql stated, I encountered the error about version of actions.
![image](https://github.com/user-attachments/assets/1307fbdb-4b64-4849-b682-89dacdd25a3b)

**Comment by animo93** [comment]
ok @thanhtamB2112004 then please raise a PR , and then let's check .
And regarding the codeQL , you can disable the workflow for now

**Comment by thanhtamB2112004** [comment]
Hi @animo93, I uploaded a PR to fix the issue, please review and provide me acknowledgment if it works well. Again thank you for letting me contribute.
